name: Test Rules

on: ['pull_request']

jobs:
  test-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Rules
        run: |
          cd tests
          npm install
          npm run tests
